spring:
  profiles:
    group:
      "local" : "oauth"
    active : local

---
spring:
  mvc.throw-exception-if-no-handler-found: true
  web.resources.add-mappings: false

  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true



logging.level:
  org.hibernate.SQL: debug